config/routes.rb
Rails.application.routes.draw do
  root to: "users#show"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get "users/show" => "users#show"
  resources :users, only: [:show]
  resources :payments
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :user
    
    enum category: {
        food: 0,
        daily: 1,
        transport: 2,
        entertainment: 3,
        education: 4,
        insurance: 5,
        medical: 6,
        communication: 7,
        utilities: 8,
        rent: 9,
        saving: 10,
        other: 11,
        salary: 12,
    }
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /payments
  # GET /payments.json
  def index
    @payments = current_user.payments
    if Payment.present?
      @all_area_money = {}
      Payment.categories_i18n.each do |_, value|
        @all_area_money[value] = 0
      end
      @search_area_money = {}
      Payment.categories_i18n.each do |_, value|
        @search_area_money[value] = 0
      end
      if params.has_key?("iuput_date(1i)")
        input_params_year = params["iuput_date(1i)"]
        input_params_month = params["iuput_date(2i)"]
      else
        input_params_year = DateTime.now.year.to_s
        input_params_month = DateTime.now.month.to_s
      end
      puts @payments
      puts "--"
      puts @search_area_money
      puts "----"
      puts @all_area_money
      puts "------"
      i = DateTime.parse("#{input_params_year}-#{input_params_month}-01")
      search_area = @payments.where(input_date: [i..i + 1.month - 1.day])
      search_area.each do |payment|
        @search_area_money[payment.category_i18n] += payment.money
      end
      all_area = @payments
      all_area.each do |payment|
        @all_area_money[payment.category_i18n] += payment.money
      end
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user_id = current_user.id

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: '正しく記録されました' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: '変更を保存しました' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: '記録は破棄されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:user_id, :input_date, :category, :money)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :日にち %>
    <%= form.date_field :input_date %>
  </div>

  <div class="field">
    <%= form.label :分類 %>
    <%= form.select :category, Payment.categories_i18n.invert %>
  </div>

  <div class="field">
    <%= form.label :金額 %>
    <%= form.number_field :money %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<div class="backcolor-default">
    <h2>入力データの編集</h2>
    <%= render 'form', payment: @payment %>

    <%= link_to '詳細表示', @payment %> |
    <%= link_to '戻る', payments_path %>
</div>

app/views/payments/index.html.erb
<div class="backgcolor-default">
  <div class="message-color">

    <p id="notice"><%= notice %></p>

    <h2>履歴確認</h2>

    <%= month_calendar(attribute: :input_date, events: @payments) do |date, payments| %>
      <%= date %>

      <% payments.each do |payment| %>
        <div>
          <%= payment.category_i18n %>
          <%= payment.money %>
          <%= link_to '編集する', edit_payment_path(payment) %>
          <%= link_to '削除する', payment, method: :delete, data: { confirm: '本当に削除しても良いですか？' } %>          
        </div>
      <% end %>
    <% end %>

    <a>選択月の分類別合計金額が表示できます。</a>
    <%= form_with url: payments_path, local: true, html: {method: 'GET'} do |form| %>
      <%= form.label :検索したい月を選択 %>
      <%= form.date_select :iuput_date, {discard_day: true} %>
      <%= form.submit "金額表示" %>
    <% end %>
    <a>ここに分類別累計金額を表示</a><br>
    <table border= "1" bgcolor = "yellow">
      <% @search_area_money.each do |key, value| %>
        <tr>
          <th><%= "#{key}" %></th>
          <td><%= "#{value}円" %></td>
        </tr>
      <% end %>

      <% search_area_money = @search_area_money.values.inject(:+) %>
      <% all_area_money = @all_area_money.values.inject(:+) %>
    </table>
    <% if search_area_money > 0 %>
      <a>あなたは今月<%= search_area_money %>円分の記録を積み重ねてきました。頑張りましたね！</a></br>
    <% end %>
    <% if all_area_money > 0 %>
      <a>あなたは今までに<%= all_area_money %>円分の記録を積み重ねてきました。えらい！</a></br>    
    <% end %>
  </div>
  <img src="/assets/the-honest-company-_UzLeRFhUPI-unsplash.jpg" width="100%" height="100%">
</div>

app/views/payments/new.html.erb
<div class="new-photo">
  <div class="message-color">
    <h2>家計簿入力</h2>

    <%= render 'form', payment: @payment %>

    <%= link_to '戻る', payments_path %>
  </div>
  <img src="/assets/kazuend-0CHEC4_wX1I-unsplash.jpg" width="100%" height:"100%">
</div>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="message-color">
  <p id="p-first">
    <strong>日にち:</strong>
    <%= @payment.input_date.strftime("%Y年%m月%d日") %>
  </p>

  <p>
    <strong>分類:</strong>
    <%= @payment.category_i18n %>
  </p>

  <p>
    <strong>金額:</strong>
    <%= @payment.money %>
  </p>

  <%= link_to '編集する', edit_payment_path(@payment) %> |
  <%= link_to '戻る', payments_path %>
</div>